stages:
  - build
  - deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build for production:
  only: master
  stage: build
  image: monachus/hugo
  only:
    - master
  script:
    - hugo --minify
    - WASM_FILE='public/js/hyphenopoly/patterns/en-gb.wasm'
    - gzip $WASM_FILE
    - GZIP_FILE='public/js/hyphenopoly/patterns/en-gb.wasm.gz'
    - mv $GZIP_FILE $WASM_FILE
    - find public/ -type f ! -iname 'index.html' ! -iname '404.html' -iname '*.html' -print0 | while read -d $'\0' f; do mv "$f" "${f%.html}"; done
  artifacts:
    paths:
      - public
    expire_in: 1 day

deploy to production:
  only: master
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws s3 sync ./public/ s3://$S3_BUCKET/ --delete --cache-control "max-age=31556952" --exclude "*" --include "js/hyphenopoly/patterns/en-gb.wasm" --content-encoding gzip --content-type application/wasm
    - aws s3 sync ./public/ s3://$S3_BUCKET/ --delete --cache-control "max-age=31556952" --exclude "*" --include "css/*" --include "js/*" --exclude js/hyphenopoly/patterns/en-gb.wasm --include "fonts/*"
    - aws s3 sync ./public/ s3://$S3_BUCKET/ --delete --exclude "css/*" --exclude "js/*" --exclude "fonts/*"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID  --paths "/*"
  artifacts:
    paths:
      - public
    expire_in: 1 day
