# Website info
title: 'Ram’s blog'
description: "Raw thoughts of a humanist"
url: 'https://blog.ramiyer.me'

future: false
google_analytics:

# Author's info
author:
  name: Ram Iyer
  url: https://ramiyer.me
  google_plus: +RamIyer07

# Build settings
markdown: kramdown
include:
  - _pages

kramdown:
  footnote_backlink: '&uarr;'

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# social links
facebook: theramiyer
twitter: theramiyer

# Permalinks
permalink: /:title/
paginate: 5

theme: typographical

# Tuning
relatedpostsenabled: true
wpm: 180
feedlimit: 10
