baseURL = "https://blog.ramiyer.me"
languageCode = "en-gb"
title = "Ram’s blog"
description = "Raw thoughts of a humanist"


theme = "typographical-hugo"

[permalinks]
  posts = "/:title/"

[Author]
  name = "Ram Iyer"
  url = "https://ramiyer.me"
  twitter = "iamramiyer"
  facebook = "iamramiyer"