baseURL = "https://blog.ramiyer.me"
languageCode = "en-gb"
title = "Ram’s blog"
description = "Raw thoughts of a humanist"
theme = "typographical-hugo"
googleAnalytics = "UA-96215433-5"

[permalinks]
posts = "/:title/"
pages = "/:title/"

[Author]
name = "Ram Iyer"
url = "https://ramiyer.me"
twitter = "iamramiyer"
facebook = "iamramiyer"

[menu]
  [[menu.main]]
  identifier = "about"
  name = ""
  title = "About"
  url = "/about/"
  weight = 0.0
  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  title = "Archive"
  url = "/archive/"
  weight = 0.0

[related]
threshold = 80.0
includeNewer = true
toLower = true
  [[related.indices]]
  name = "tags"
  weight = 100.0