baseURL = "https://blog.ramiyer.me"
languageCode = "en-GB"
title = "Ram’s blog"
theme = "typographical"

[params]
  description = "For what it’s worth"
# enableTypographicalHyphenation = true
  enableAutoAttribution = true
  enableDevanagari = true
  enableSharing = true
# fbAppId = "1004129106665557"
# fbAccessToken = "c0ccefea32b8675b177da298022b672c"
  applePodcastsId = "id1448518505"
  googlePodcastsId = "aHR0cHM6Ly9hbmNob3IuZm0vcy8xNGNjYTI0L3BvZGNhc3QvcnNz"
  privacyPolicyUrl = "/privacy/"

[params.mastodon]
  server = "mastodon.online"
  username = "ramiyer"

[params.copyright]
  icon = "<i class=\"fab fa-creative-commons\"></i>&thinsp;<i class=\"fab fa-creative-commons-by\"></i>&thinsp;<i class=\"fab fa-creative-commons-nc\"></i>&thinsp;<i class=\"fab fa-creative-commons-sa\"></i>"
  message = "[Ram's blog](https://blog.ramiyer.me) by [Ram Iyer](https://ramiyer.me) is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)."

[params.dropCap]
  enable = true

[params.contactForm]
  id = 'xjvpplyr'

[params.plausible]
  enable = true
  domain = "blog.ramiyer.me"
  custom_js_domain = "analytics.ramiyer.me"
  public_dashboard = true

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[permalinks]
  post = "/:title/"
  page = "/:title/"

[Author]
  name = "Ram Iyer"
  url = "https://ramiyer.me"
  twitter = "iamramiyer"
  facebook = "iamramiyer"
  patreon = "ramiyer"

[menu]
  [[menu.main]]
  identifier = "archive"
  pre = "<i class='fas fa-archive'></i>"
  title = "Archive"
  url = "/archive/"
  weight = 1
  [[menu.main]]
  identifier = "youtube"
  pre = "<i class='fab fa-youtube'></i>"
  title = "YouTube"
  url = "https://youtube.com/ramiyer"
  weight = 2
  [[menu.main]]
  identifier = "podcast"
  pre = "<i class='fas fa-headphones-alt'></i>"
  title = "Podcast"
  url = "https://anchor.fm/ramiyer"
  weight = 3
  [[menu.main]]
  identifier = "about"
  pre = "<i class='fas fa-info'></i>"
  title = "About"
  url = "/about/"
  weight = 4

[related]
threshold = 80.0
includeNewer = true
toLower = true
  [[related.indices]]
  name = "tags"
  weight = 100.0

[outputs]
  home = [ "HTML", "JSON", "RSS"]
  page = [ "HTML"]

canonifyURLs = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false

[sitemap]
    changefreq = "weekly"
    priority = 0.5
